### ISSUE TITLE
Country Code text

### ISSUE THREAD

**Issue by rishi2062** [lugvitc/lugvitc.github.io#20]
Sometimes due to auto fill reason, mobile number got submitted in the country code section due to which sites gives an error dialog of there was an error which also don't give much clarity of where is the error
either we can clarify error or make country code as a drop down menu

**Comment by 3V3RYONE** [comment]
Thanks for opening this, changed country code max length to 7, so autofill won't be able to put 10 digit phone number into the country code field. Marking this as resolved now.
